### ISSUE TITLE
TODO List #1

### ISSUE THREAD

**Issue by fresh-avocado** [fresh-avocado/AVL#1]
- [x] `predecessor`
- [x] `delete`
- [ ] corregir la mantenibilidad y legibilidad del código, ya que ahorita no está tan mantenible, viola el principio DRY y de reusabilidad
- [x] añadir atributo `parent` a los nodos para que `successor` y `predecessor` sean más simples
- [x] añadir `clang-tidy`, `clang-format`, `git hooks` (pre-commit y commit-msg) y carpeta de tests
- [x] carpeta `src` y `test` y editar `Makefile` _recipes_ correspondientes
- [ ] añadir _thread safety_, es decir, que esta ED pueda ser manipulada por múltiples _threads_ a la vez y que esto no impacte la consistencia de la ED
- [x] poner interfaz en `.hpp` e implementación en `.cpp`
- [x] añadir `template<typename T, typename U>`, `T` para el _key_ y `U` para el _satellite data_
- [x] añadirle _type traits_ a tanto `T` y `U` para que sean _copy constructable_
